-- Seed idempotente do exemplo "O homem do churrasco" (Dia dos Pais, F2-5).
-- Filha adulta homenageando o pai. Upsert por seoSlug: re-aplicar atualiza o
-- conteúdo sem duplicar. payload no schema de Gift.payload, sem contador,
-- com 4 fotos no R2 (assets) associadas aos momentos via photoAssetId.
INSERT INTO "Example" ("id", "persona", "name", "occasion", "payload", "seoSlug", "sortOrder", "active", "createdAt") VALUES
  ('ex_homem_churrasco', 'pai', 'O homem do churrasco', 'pais',
   '{"title":"O homem do churrasco (e do resto todo)","recipientName":"Seu Marcos","senderName":"sua filha","assets":[{"id":"ph_bike","type":"image","r2Key":"gifts/1b3c29e848e277642d8ae2ebbdbb5603.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/1b3c29e848e277642d8ae2ebbdbb5603.webp","order":0},{"id":"ph_churrasco","type":"image","r2Key":"gifts/b52055c9ae9f0748b6a17dae3ef074be.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/b52055c9ae9f0748b6a17dae3ef074be.webp","order":1},{"id":"ph_call","type":"image","r2Key":"gifts/d234a34e73286670c1416007d6d6e46d.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/d234a34e73286670c1416007d6d6e46d.webp","order":2},{"id":"ph_carro","type":"image","r2Key":"gifts/9cb2554fb6f777bbc1420fc8901c0936.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/9cb2554fb6f777bbc1420fc8901c0936.webp","order":3}],"timeline":[{"date":"1999","title":"A bicicleta","description":"Você soltou o banco sem avisar. Funcionou. Nunca te perdoei. Obrigada.","photoAssetId":"ph_bike"},{"date":"2005","title":"Toda festa da escola","description":"Você lá, na primeira fileira, filmando na horizontal errada."},{"date":"2013","title":"Minha primeira decepção amorosa","description":"Você não disse nada. Só fez churrasco. Era exatamente o que eu precisava.","photoAssetId":"ph_churrasco"},{"date":"2020","title":"A videochamada","description":"Você aprendeu só pra me ver na pandemia. E passou 3 meses me mostrando o teto.","photoAssetId":"ph_call"},{"date":"2026","title":"Hoje","description":"Levo o carro pra você \"dar uma olhada\" só pra ter desculpa de te ver.","photoAssetId":"ph_carro"}],"stats":[{"value":700,"suffix":"churrascos de domingo","label":"e a fome junto"},{"value":100,"suffix":"% das caronas","label":"atendidas na hora"},{"value":0,"suffix":"vezes um \"eu avisei\"","label":"mesmo tendo avisado"}],"letter":"Pai, você nunca foi de falar \"eu te amo\". Você fala \"calibrou o pneu?\", \"avisa quando chegar\", \"tem picanha aqui de domingo\". Demorei pra entender que era tudo a mesma frase. Obrigada por me soltar da bicicleta na hora certa e por nunca me soltar de verdade. Todo domingo, quando sinto cheiro de churrasco, é de você que eu lembro. Feliz Dia dos Pais, Seu Marcos. Calibrei o pneu, sim. — Sua filha","closingMessage":"◄◄ rebobina: você sempre esteve lá","spotifyTrackUrl":"https://open.spotify.com/track/6dv68ZqYYKVkXlInvL2Yno","theme":"vhs"}'::jsonb,
   'pais-homem-do-churrasco', 0, true, CURRENT_TIMESTAMP)
ON CONFLICT ("seoSlug") DO UPDATE SET
  "persona" = EXCLUDED."persona",
  "name" = EXCLUDED."name",
  "occasion" = EXCLUDED."occasion",
  "payload" = EXCLUDED."payload",
  "sortOrder" = EXCLUDED."sortOrder",
  "active" = EXCLUDED."active";
