/**
 * Rebobinaí ◄◄ — dados dos 20 exemplos restantes da galeria (F2-5, lote 2),
 * transcritos de docs/EXEMPLOS-REBOBINADAS.md para o schema do Gift.payload
 * (padrão da migração 20260707120000_example_1095_dias).
 *
 * Convenções:
 * - photos: n = índice da foto no R2 (seed/exemplos/<slug>/<n>.png);
 *   `tl` = índice (1-based) do momento da timeline que recebe a foto.
 * - stats com `auto: 'days_since_counter'` são calculadas no render.
 * - Sem spotifyTrackUrl (adicionar depois, exige URL válida).
 */
export const R2_BASE = 'https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev';

export const EXAMPLES = [
  // ========================= NAMORO =========================
  {
    slug: 'namoro-do-match', persona: 'namorado', occasion: 'namorados',
    name: 'Casal do aplicativo', sortOrder: 20,
    title: 'Do match ao pra sempre', recipient: 'Rê', sender: 'Dudu',
    photos: [{ n: 1, tl: 2 }, { n: 2, tl: 3 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '2024', title: 'O match', description: 'Sua bio dizia "não curto papo furado". Eu mandei um papo furadíssimo. Funcionou.' },
      { date: '2024', title: 'O hambúrguer do teste', description: 'Você pediu o mais caro "pra testar se eu ia embora". Fiquei.' },
      { date: '2024', title: 'Cerimônia de desinstalação', description: 'Apagamos os aplicativos juntos, um segurando o celular do outro.' },
      { date: '2025', title: 'O acostamento mais romântico da serra', description: 'Pneu furado, 2h de espera e a melhor conversa da minha vida.' },
      { date: 'hoje', title: 'Melhor update', description: '2 anos de "cê viu isso?" mandado ao mesmo tempo.' },
    ],
    stats: [
      { value: 1, suffix: 'arraste', label: 'pro lado que mudou tudo' },
      { value: 730, suffix: 'dias', label: 'de conversa que não acabou' },
      { value: 3412, suffix: 'memes', label: 'trocados (e contando)' },
    ],
    letter: 'Rê, todo mundo ri quando conta que a gente veio de um aplicativo. Eu também rio — de sorte. Porque no meio de mil perfis eu achei a única pessoa que responde meme com meme melhor, que transforma pneu furado em história boa e silêncio em lugar confortável. Você foi o único match que virou casa. Dois anos, e eu ainda arrastaria pro lado de novo, sempre. — Dudu',
  },
  {
    slug: 'namoro-primeiro-ano', persona: 'namorada', occasion: 'namorados',
    name: 'Primeiro ano de namoro', sortOrder: 21,
    title: '365 dias do nosso primeiro beijo', recipient: 'Ícaro', sender: 'Marina',
    counter: { targetDate: '2025-07-12', label: 'dias desde que eu perdi a linha do "só amigos"' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 4 }, { n: 5, tl: 5 }],
    timeline: [
      { date: '07/2025', title: 'A festa onde tudo desandou', description: 'Pro lado certo. Uma amizade perfeitamente boa, estragada no melhor estilo.' },
      { date: '07/2025', title: 'Primeiro café da manhã', description: 'Você queimou o pão e eu menti que estava ótimo.' },
      { date: '12/2025', title: 'O dia da praia em que choveu', description: 'Melhor dia de praia da história.' },
      { date: '03/2026', title: 'Você conhecendo minha mãe', description: 'Ela te aprovou antes de mim.' },
      { date: 'hoje', title: 'A gente', description: 'Ainda com cara de primeiro beijo.' },
    ],
    stats: [{ auto: 'days_since_counter', label: 'dias de nós' }],
    letter: 'Ícaro, faz um ano que a gente estragou uma amizade perfeitamente boa — e foi a melhor decisão que já tomamos. Um ano de primeiras vezes: primeiro café queimado, primeira chuva na praia, primeira vez que eu percebi que "te amo" escapa sozinho quando é verdade. Obrigada por tornar o comum a melhor parte do meu dia. Que a gente nunca perca a cara de primeiro beijo. — Marina',
    closing: '◄◄ aperta o play na nossa história',
  },
  {
    slug: 'namoro-a-gente-e-a-nina', persona: 'namorado', occasion: 'namorados',
    name: 'O casal e a cachorra', sortOrder: 22,
    title: 'A gente + a Nina', recipient: 'Paula', sender: 'Vitor',
    counter: { targetDate: '2022-07-12', label: 'dias de matilha' },
    photos: [{ n: 1, tl: 3 }, { n: 2, tl: 4 }, { n: 3, tl: 5 }, { n: 4 }],
    timeline: [
      { date: 'ano 1', title: 'Só a gente', description: 'Dois delivery e uma série que nunca terminamos.' },
      { date: 'ano 2', title: 'O anúncio "só pra ver"', description: 'Você me mandou um anúncio de adoção "só pra ver". Aham. Só pra ver.' },
      { date: 'o dia da Nina', title: 'Ela chegou', description: 'Vomitou no carro em 15 minutos de estrada. Já era da família.' },
      { date: 'ano 3', title: 'O tênis (in memoriam)', description: 'Ela destruiu seu tênis favorito. Você a perdoou em 4 segundos, recorde mundial.' },
      { date: 'hoje', title: 'Três habitantes', description: 'Cama de casal com três habitantes, dois pagando aluguel.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias juntos' },
      { value: 730, suffix: 'passeios', label: 'de coleira' },
      { value: 1, suffix: 'tênis', label: 'in memoriam' },
    ],
    letter: 'Paula, quatro anos e eu ainda não sei o que amo mais: acordar com você ou com a Nina pisando na minha cara às 6h. Mentira, sei sim. Obrigado por ter mandado aquele anúncio "só pra ver" e por transformar nosso apartamento em lar com pelo no sofá. Você cuida de nós dois de um jeito que me faz querer ser tão bom quanto a Nina acha que eu sou. — Vitor',
  },
  // ======================= CASAMENTO ========================
  {
    slug: 'casamento-primeiro-ano', persona: 'casamento', occasion: 'casamento',
    name: 'Primeiro ano de casados', sortOrder: 23,
    title: 'Nosso primeiro ano de alianças', recipient: 'Tom', sender: 'Bea',
    counter: { targetDate: '2025-07-11', label: 'dias de "meu marido" e "minha esposa" sem cansar' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 4 }, { n: 5, tl: 5 }],
    timeline: [
      { date: '07/2025', title: 'O sim', description: 'Sua voz falhou e a minha sumiu.' },
      { date: '07/2025', title: 'A dança ensaiada 14 vezes', description: 'Erramos mesmo assim. Os convidados amaram.' },
      { date: '07/2025', title: 'O voo perdido', description: 'Lua de mel: perdemos o voo e ganhamos uma noite em Lisboa.' },
      { date: '08/2025', title: 'Primeira geladeira nossa', description: 'Enchemos de ímã e de planos.' },
      { date: 'hoje', title: '365 dias depois', description: 'Mesma vontade de casar de novo.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de casados' },
      { value: 1, suffix: 'voo perdido', label: 'que virou história' },
      { value: 52, suffix: 'sextas', label: 'de pizza no sofá' },
    ],
    letter: 'Tom, um ano atrás sua voz falhou no altar e eu entendi tudo o que você não conseguiu falar. Este primeiro ano teve mais boleto que lua de mel, mais rotina que festa — e ainda assim, casar com você continua sendo a coisa mais certa que eu já fiz. Obrigada por transformar segunda-feira em lugar bom. Que a gente erre a dança juntos pra sempre. — Bea',
  },
  {
    slug: 'casamento-de-2-viramos-4', persona: 'casamento', occasion: 'casamento',
    name: '10 anos, com filhos', sortOrder: 24,
    title: 'De 2 viramos 4 (e um papagaio)', recipient: 'Dani', sender: 'Fê',
    counter: { targetDate: '2016-06-04', label: 'dias de time em campo' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 5 }, { n: 5, tl: 6 }],
    timeline: [
      { date: '2016', title: 'Festa pequena, planos gigantes', description: 'Casamos no quintal e ninguém queria ir embora.' },
      { date: '2018', title: 'O positivo no banheiro', description: 'Você gritou tão alto que a vizinha bateu na parede.' },
      { date: '2019', title: 'Chegou o Théo', description: 'Dormir virou lenda urbana.' },
      { date: '2022', title: 'Chegou a Alice, com pressa', description: 'Quase nasceu no Uber. O motorista ganhou 5 estrelas e terapia.' },
      { date: '2024', title: 'O papagaio Juca', description: 'Herdado do seu tio. Fala "cadê o boleto" melhor que nós dois.' },
      { date: '2026', title: '10 anos', description: 'A casa é barulhenta, bagunçada e exatamente o que a gente pediu.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de casados' },
      { value: 2, suffix: 'humanos', label: 'produzidos' },
      { value: 14000, suffix: 'fraldas', label: 'estimativa conservadora' },
    ],
    letter: 'Dani, dez anos atrás eu prometi te amar na alegria e na tristeza. Ninguém avisou da terceira opção: na exaustão. E olha que descoberta — é nela que eu mais te amo. Te vendo domar birra às 3h da manhã, rir no meio do caos, segurar a nossa casa com uma mão e a minha mão com a outra. A gente virou 4 (e um papagaio), mas no fim do dia, quando todo mundo dorme, ainda somos aqueles 2. Sempre seremos. — Fê',
  },
  {
    slug: 'casamento-bodas-ouro', persona: 'casamento', occasion: 'casamento',
    name: 'Bodas de ouro', sortOrder: 25,
    title: '50 anos de nós', recipient: 'Vó Cida & Vô Antônio', sender: 'seus netos',
    counter: { targetDate: '1976-06-12', label: 'dias de mão dada' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 4 }, { n: 3, tl: 5 }, { n: 4, tl: 2 }, { n: 5, tl: 6 }],
    timeline: [
      { date: '1974', title: 'O baile', description: 'Vô pediu uma dança e pisou no pé dela duas vezes. Ela aceitou a terceira.' },
      { date: '1976', title: 'O casamento', description: 'Na cidade pequena. A festa acabou quando acabou a sanfona.' },
      { date: 'anos 80', title: 'Quatro filhos e uma venda', description: 'E a fama do melhor pão da rua.' },
      { date: 'anos 90', title: 'Recomeço na capital', description: 'Atrás dos filhos. Recomeçar aos 45 também é coragem.' },
      { date: '2010', title: 'Primeira neta', description: 'Vô inaugurou o posto de avô-babão que ocupa até hoje.' },
      { date: '2026', title: 'A rosa do baile', description: 'Vô ainda guarda a rosa (seca) do baile. A gente viu.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de casados' },
      { value: 4, suffix: 'filhos', label: 'e uma multidão de netos' },
      { value: 1, suffix: 'rosa', label: 'guardada desde 1974' },
    ],
    letter: 'Vó, vô: metade da família nem tinha nascido quando vocês já eram história. A gente cresceu ouvindo do baile, da sanfona, do pão que sustentou quatro filhos. Mas o que a gente mais aprendeu foi olhando: o senhor descascando laranja pra ela todo santo dia, ela guardando o pedaço maior pro senhor. Cinquenta anos e vocês ainda se escolhem no café da manhã. Se amor tiver receita, a gente quer a de vocês. — Seus netos (todos, até o que só pensa em videogame)',
    closing: '◄◄ algumas fitas nunca desgastam',
  },
  // ========================== PAIS ==========================
  {
    slug: 'pais-primeiro-dia', persona: 'pai', occasion: 'pais',
    name: 'Primeiro Dia dos Pais', sortOrder: 26,
    title: 'Seu primeiro Dia dos Pais', recipient: 'Gabriel', sender: 'Miguel (e a mamãe)',
    counter: { targetDate: '2025-12-14', label: 'dias sendo o pai do Miguel' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 4 }, { n: 5, tl: 5 }],
    timeline: [
      { date: 'dia 1', title: 'O dia em que você virou pai', description: 'E eu me apaixonei de novo.' },
      { date: 'semana 1', title: 'Primeira troca de fralda', description: '22 minutos, 3 tentativas, 1 vitória.' },
      { date: 'mês 2', title: 'Geneticamente comprovado', description: 'Vocês dois dormindo igual, de boca aberta.' },
      { date: 'mês 4', title: 'O banho', description: 'Molhou mais você do que ele.' },
      { date: 'mês 7', title: 'Primeiro "papapa"', description: 'Você jura que foi "papai". Deixa.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de paternidade' },
      { value: 1400, suffix: 'madrugadas', label: 'interrompidas sem perder a ternura' },
      { value: 1, suffix: 'riso', label: 'que valeu tudo' },
    ],
    letter: 'Pai, eu ainda não sei falar, então a mamãe está escrevendo. Ela mandou dizer que te ver comigo no colo é a coisa mais bonita que ela já viu — e ela viu o mar. Que você acorda de madrugada sem reclamar (quase), que canta desafinado igual eu gosto, e que eu ganhei na loteria dos pais. Feliz primeiro Dia dos Pais. Dos infinitos que vêm por aí, esse é o que você nunca vai esquecer. — Miguel (7 meses, 8 quilos de amor por você)',
  },
  {
    slug: 'pais-tecnico-de-todas', persona: 'pai', occasion: 'pais',
    name: 'Pai e filho, mesmo time', sortOrder: 27,
    title: 'Meu técnico de todas as horas', recipient: 'pai', sender: 'seu eterno camisa 10',
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '2003', title: 'Minha primeira bola', description: 'Você narrou meu primeiro gol contra o portão como se fosse final de Copa.' },
      { date: '2008', title: 'Nunca faltou', description: 'Você saía do turno cansado e ainda ia comigo pro treino. Eu contei.' },
      { date: '2014', title: 'O 7x1 junto', description: '"Filho, tem derrota que vira história." Uso isso pra tudo até hoje.' },
      { date: '2018', title: 'O joelho e a frase', description: '"Muda o sonho, não muda o time que a gente é."' },
      { date: '2026', title: 'Mesmo sofá, mesmo time', description: 'E eu não trocaria por camarote nenhum.' },
    ],
    stats: [
      { value: 480, suffix: 'treinos', label: 'com plateia de 1' },
      { value: 23, suffix: 'anos', label: 'de arquibancada' },
      { value: 1, suffix: 'lema', label: 'pra vida inteira' },
    ],
    letter: 'Pai, você nunca me cobrou gol. Me cobrou caráter. Aprendi a perder no futebol e a ganhar na vida ouvindo você narrar meus erros como se fossem lances de gênio. Quando meu joelho estourou junto com meu sonho, você não deixou estourar o resto. "Muda o sonho, não muda o time." Nosso time, velho, não rebaixa nunca. Feliz Dia dos Pais. — Seu camisa 10',
  },
  {
    slug: 'pais-pai-e-quem-fica', persona: 'pai', occasion: 'pais',
    name: 'Pai de criação', sortOrder: 28,
    title: 'Pai é quem fica', recipient: 'Júlio', sender: 'teu moleque',
    counter: { targetDate: '2010-03-20', label: 'dias desde que você escolheu a gente' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '2010', title: 'O presente certo', description: 'Você apareceu no aniversário de 8 anos com o presente certo: paciência.' },
      { date: '2011', title: 'Panqueca aos sábados', description: 'Eu te testei por meses. Você respondeu com panqueca. Vitória sua.' },
      { date: '2015', title: 'Responsável pelo aluno', description: 'Reunião de escola: você levantou a mão sem hesitar um segundo.' },
      { date: '2019', title: 'Aulas de direção', description: 'Sem gritar nenhuma vez. Um monge. Um santo. Um pai.' },
      { date: '2024', title: '"Os pais do formando"', description: 'Você olhou pros lados. Era você, Júlio. Sempre foi.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de presença' },
      { value: 700, suffix: 'panquecas', label: 'de sábado (estimativa)' },
      { value: 0, suffix: 'vezes', label: 'que você faltou' },
    ],
    letter: 'Júlio, você chegou sem manual e sem obrigação. Podia ter sido só "o namorado da minha mãe" — escolheu ser presença, panqueca de sábado, mão levantada em reunião de escola. Sangue não te fez meu pai. Você se fez, dia após dia, ficando. Na minha formatura, quando disseram "os pais", eu nem olhei pros lados: já sabia. Feliz Dia dos Pais pra quem me ensinou que família é verbo. — Teu moleque',
    closing: '◄◄ família é quem aperta o play com você',
  },
  // ========================== MÃES ==========================
  {
    slug: 'maes-primeiro-dia', persona: 'mãe', occasion: 'maes',
    name: 'Primeiro Dia das Mães', sortOrder: 29,
    title: 'Seu primeiro Dia das Mães', recipient: 'Amanda', sender: 'Helena (ditado pro papai)',
    counter: { targetDate: '2025-11-08', label: 'dias sendo a mãe da Helena' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 4 }, { n: 5, tl: 5 }],
    timeline: [
      { date: 'dia 1', title: 'O primeiro colo', description: 'Você tremia e acertava ao mesmo tempo.' },
      { date: 'madrugada 47', title: 'As duas na poltrona', description: 'Vocês duas dormindo juntas. Eu tirei a foto chorando.' },
      { date: 'mês 3', title: 'Primeiro banho de sol', description: 'Você conferiu o protetor 6 vezes.' },
      { date: 'mês 5', title: 'A primeira risada', description: 'Foi pra você. Óbvio.' },
      { date: 'mês 8', title: 'Olhares intraduzíveis', description: 'Mãe e filha: 8 meses de olhares que eu nunca vou saber traduzir.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de mãe' },
      { value: 1400, suffix: 'madrugadas', label: 'sem perder a ternura' },
      { value: 1, suffix: 'riso', label: 'que valeu tudo' },
    ],
    letter: 'Mãe, o papai está escrevendo porque eu só sei morder. Ele disse pra te contar o que ele vê: que você virou mãe no segundo em que me viu e nunca mais desligou. Que canta pra mim mesmo morrendo de sono, que aprendeu meus choros como quem aprende um idioma. Ele disse que sempre te amou, mas que te ver ser minha mãe é outra coisa — é assistir um super-herói de pijama. Feliz primeiro Dia das Mães. — Helena (e o papai, chorando no canto)',
  },
  {
    slug: 'maes-dose-dupla-de-longe', persona: 'mãe', occasion: 'maes',
    name: 'Mãe à distância', sortOrder: 30,
    title: '919 km e nenhuma distância', recipient: 'mãe', sender: 'seu menino',
    counter: { targetDate: '2021-02-08', label: 'dias matando a saudade em áudio de 4 minutos' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 3 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '2021', title: 'O abraço na rodoviária', description: 'Você disse "vai, filho" com a voz firme e a mão tremendo.' },
      { date: '2022', title: 'O Maps da saudade', description: 'Descobri que você aprendeu a usar o Maps só pra "ver minha rua" de vez em quando.' },
      { date: '2023', title: 'Áudios de 4 minutos', description: '1 de recado, 3 de novela da vizinhança. Eu ouço tudo. Duas vezes.' },
      { date: '2024', title: 'A mala de comida', description: 'Você veio de surpresa: 2kg de roupa, 8kg de comida congelada.' },
      { date: 'todo dia', title: 'O despertador favorito', description: '"Bom dia meu filho, Deus te abençoe 🌹", sem falhar.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de saudade vencida' },
      { value: 919, suffix: 'km', label: 'que o Maps insiste em mostrar' },
      { value: 8, suffix: 'kg', label: 'de comida congelada por visita' },
    ],
    letter: 'Mãe, 919 km é o número que o Maps mostra. Mentira dele. Você tá aqui todo dia: no tempero que eu tento imitar, no áudio que eu guardo, na rosa 🌹 das 7h da manhã. Você me soltou pro mundo com a mão tremendo e nunca deixou eu me sentir solto. Um dia eu volto, ou te trago — mas até lá, saiba: filho que voa alto é porque a mãe construiu o ninho no lugar certo. Te amo. — Seu menino',
  },
  {
    slug: 'maes-rainha-da-casa', persona: 'mãe', occasion: 'maes',
    name: 'A mãe que segurou tudo', sortOrder: 31,
    title: 'A rainha desta casa', recipient: 'Dona Marta', sender: 'os 3 que ela criou no braço',
    photos: [{ n: 1, tl: 2 }, { n: 2, tl: 3 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '2004', title: 'Ficamos só nós quatro', description: 'Você disse "ninguém vai faltar nada". Cumpriu com juros.' },
      { date: '2004–2012', title: 'Dois empregos, presença total', description: 'Marmita na bolsa e TODA reunião de escola. A gente nunca soube como.' },
      { date: '2013', title: 'O primeiro diploma da família', description: 'Você chorou tanto que a foto saiu tremida. Emolduramos assim mesmo.' },
      { date: '2018', title: 'O primeiro mar', description: 'A gente se juntou e te deu a praia. Aos 52, seu sorriso ganhou da paisagem.' },
      { date: '2026', title: 'A mesa cheia', description: 'Três filhos formados, casa cheia de neto e a mesma frase: "ninguém vai faltar nada".' },
    ],
    stats: [
      { value: 3, suffix: 'filhos', label: 'criados no braço' },
      { value: 2, suffix: 'empregos', label: 'por 8 anos' },
      { value: 0, suffix: 'reuniões', label: 'de escola perdidas' },
    ],
    letter: 'Mãe, a gente cresceu te vendo fazer conta no caderninho e mágica no fogão. Você transformou pouco em suficiente e suficiente em festa. Nunca soubemos como você estava em todas — trabalho, escola, plantão de febre — sendo uma só. Hoje, cada conquista nossa tem sua digital. O diploma é seu. A casa é sua. O mar, a gente devia ter te mostrado antes. Obrigado por nunca deixar faltar o principal. Era você. — Seus 3',
    closing: '◄◄ replay pra quem nunca pausou',
  },
  // ========================== AVÓS ==========================
  {
    slug: 'avos-cheiro-de-bolo', persona: 'avó', occasion: 'avos',
    name: 'A casa da avó', sortOrder: 32,
    title: 'A casa da vó tem cheiro de bolo', recipient: 'Vó Terezinha', sender: 'a neta que roubava a raspa da panela',
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '1998', title: '"Devagar, senão desanda"', description: 'Suas mãos me ensinando a mexer o bolo. Aplico isso na vida.' },
      { date: '2003', title: 'Férias na sua casa', description: 'Café com bolacha às 15h, novela às 18h, benzida antes de dormir.' },
      { date: '2008', title: 'O pote de margarina', description: 'Você guardava o troco num pote "pro lanche da minha neta".' },
      { date: '2015', title: '"Vem que eu resolvo"', description: 'Te liguei chorando da faculdade. Você resolveu. Com bolo.' },
      { date: '2026', title: 'A receita que não replica', description: 'Faço seu bolo na minha casa. Nunca fica igual. Falta você.' },
    ],
    stats: [
      { value: 2000, suffix: 'tardes', label: 'de café às 15h' },
      { value: 1, suffix: 'pote', label: 'de margarina que era cofre' },
      { value: 28, suffix: 'anos', label: 'de colo garantido' },
    ],
    letter: 'Vó, cientistas deviam estudar sua casa: o tempo passa diferente aí. A tarde dura mais, o problema encolhe, o bolo nunca acaba. Você me benzeu, me alimentou e me ensinou que amor se mede em fatia — sempre generosa, sempre a maior pra mim. Tento fazer seu bolo e não sai igual. Tudo bem. Receita boa a gente não replica, visita. Feliz Dia dos Avós pra melhor parte da minha infância — e da minha vida adulta também. — Sua neta',
    closing: '◄◄ rebobina pra tarde na casa da vó',
  },
  {
    slug: 'avos-historias-do-vo', persona: 'avô', occasion: 'avos',
    name: 'As histórias do avô', sortOrder: 33,
    title: 'As histórias do vô (todas as 7)', recipient: 'Vô Chico', sender: 'os netos que fingem que nunca ouviram',
    photos: [{ n: 1, tl: 2 }, { n: 2, tl: 1 }, { n: 3, tl: 3 }, { n: 4, tl: 4 }],
    timeline: [
      { date: 'clássico nº 1', title: 'O peixe-botijão', description: '"Era do tamanho de um botijão." Cresce 10cm por ano. Amamos.' },
      { date: 'clássico nº 2', title: 'A pescaria da soneca', description: 'Você me deixou dormir no barco e disse pra vó que eu "ajudei muito".' },
      { date: 'clássico nº 3', title: 'O rádio de pilha', description: 'Copa de 70 na sua voz é melhor que qualquer transmissão.' },
      { date: 'clássico nº 4', title: 'A bicicleta eterna', description: 'Consertada 14 vezes em vez de deixar comprarem nova. "Essa aqui tem história."' },
      { date: 'a que você não conta', title: 'As ajudas em silêncio', description: 'Quantas vezes ajudou todo mundo sem contar. Essa a gente conta por você.' },
    ],
    stats: [
      { value: 7, suffix: 'histórias', label: 'em rotação infinita' },
      { value: 340, suffix: 'pescarias', label: 'e contando' },
      { value: 14, suffix: 'consertos', label: 'na mesma bicicleta' },
    ],
    letter: 'Vô, a gente sabe as suas histórias de cor: o peixe-botijão, o gol narrado no rádio, a viagem de caminhão. E sabe por que a gente pede de novo? Não é pela história. É pra ver o senhor contando — o olho que acende, a mão que desenha o tamanho do peixe (sempre maior). Suas histórias são o nosso lugar favorito. Continua contando, vô. A gente continua fingindo surpresa. Combinado? — Seus netos',
  },
  {
    slug: 'avos-quatro-geracoes', persona: 'avó', occasion: 'avos',
    name: 'Bisavó, raiz de tudo', sortOrder: 34,
    title: 'Quatro gerações de nós', recipient: 'Bisa Maria', sender: 'suas 4 gerações',
    counter: { targetDate: '1932-05-03', label: 'dias de Dona Maria no mundo — e o mundo agradece' },
    photos: [{ n: 1, tl: 2 }, { n: 2, tl: 4 }, { n: 3, tl: 3 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '1932', title: 'Nasce Maria', description: 'No interior, numa casa de chão batido. Ninguém avisou o século do que vinha.' },
      { date: '1955', title: '6 filhos, enxada e fé', description: 'Sobrou amor pra plantação inteira.' },
      { date: '1987', title: 'Chegam os netos: 14', description: 'Você decorou aniversário, apelido e comida favorita de todos.' },
      { date: '2012', title: 'Chegam os bisnetos', description: 'Você, de touca de lã em pleno verão: "criança precisa de vó por perto".' },
      { date: '2026', title: 'A cabeceira da mesa', description: '94 anos, 4 gerações, 1 mesa que não cabe mais ninguém — e você rindo.' },
    ],
    stats: [
      { value: 31, suffix: 'pessoas', label: 'que existem porque você aguentou firme' },
      { value: 4, suffix: 'gerações', label: 'na mesma mesa' },
      { value: 94, suffix: 'anos', label: 'de cabeceira' },
    ],
    letter: 'Bisa, a senhora começou num chão batido e construiu chão pra todos nós pisarmos. São 6 filhos, 14 netos, 11 bisnetos — 31 pessoas que existem porque a senhora aguentou o que a gente nem imagina e sorriu mesmo assim. Quando a mesa enche no domingo e não cabe cadeira, olha bem: aquilo é a sua obra. A gente não é família grande, Bisa. A gente é a senhora, multiplicada. — Suas 4 gerações',
    closing: '◄◄ essa fita começou em 1932 e só melhora',
  },
  {
    slug: 'avos-primeira-viagem', persona: 'avó', occasion: 'avos',
    name: 'Avós de primeira viagem', sortOrder: 35,
    title: 'O estágio mais feliz do mundo', recipient: 'vovós Neusa & Roberto', sender: 'a estagiária Cecília (1 ano)',
    counter: { targetDate: '2025-07-10', label: 'dias no cargo de avós — desempenho: acima do esperado' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 4 }, { n: 5, tl: 5 }],
    timeline: [
      { date: 'dia 1', title: 'Briga (educada) por colo', description: 'Vocês dois disputando quem segura primeiro.' },
      { date: 'semana 2', title: 'O berço "sem manual"', description: 'Sobrou parafuso. O berço, milagrosamente, funciona.' },
      { date: 'mês 1', title: 'O papo do "não vou mimar"', description: 'Durou exatas 48 horas, vó.' },
      { date: 'mês 10', title: 'A primeira palavra VIP', description: 'Depois de mamãe e papai: "vovó". Comemoraram por 3 dias.' },
      { date: '1 ano', title: 'Bolo na cara, coração cheio', description: '1 ano de Cecília, 1 ano dos avós mais coruja do hemisfério.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias no cargo' },
      { value: 4380, suffix: 'fotos', label: 'da neta no grupo da família' },
      { value: 2, suffix: 'aposentadorias', label: 'dedicadas a 1 bebê' },
    ],
    letter: 'Pai, mãe: a gente achou que conhecia vocês. Aí a Cecília nasceu e apareceram duas pessoas novas — o homem que fala fininho e a mulher que compra vestido tamanho 1 "porque estava com o preço bom" toda semana. Ver vocês serem avós é rever nossa infância de camarote: o mesmo colo, a mesma paciência, o dobro do deboche. Cecília ganhou os melhores. E nós, que já sabíamos, confirmamos. — Seus filhos (pais da chefinha)',
  },
  // ======================== AMIZADE =========================
  {
    slug: 'amizade-desde-a-escola', persona: 'amigas', occasion: 'amizade',
    name: 'Melhores amigas da escola', sortOrder: 36,
    title: '15 anos dividindo o lanche e a vida', recipient: 'Carol', sender: 'Bia, sua sócia emocional desde 2011',
    counter: { targetDate: '2011-02-07', label: 'dias de sociedade sem contrato' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 3 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }, { n: 5, tl: 6 }],
    timeline: [
      { date: '2011', title: 'A cadeira vazia', description: 'Você sentou do meu lado porque "a cadeira estava vazia". Nunca mais levantou.' },
      { date: '2013', title: 'Piada interna nº 1', description: 'O trote que a gente sofreu junto virou a piada nº 1 (de 947).' },
      { date: '2016', title: 'Formatura', description: 'Choramos achando que ia ser difícil manter contato. Inocentes.' },
      { date: '2019', title: 'Sorvete às 2h da manhã', description: 'Você atravessou a cidade porque um boy me fez chorar. Ele era um erro. Você, um acerto.' },
      { date: '2023', title: 'Madrinha', description: 'Seu discurso constrangedor segue sendo o melhor momento da festa.' },
      { date: '2026', title: '15 anos', description: 'Novas cidades, novos empregos, mesmo grupo de figurinhas. Mesma gente.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de amizade' },
      { value: 947, suffix: 'piadas', label: 'internas catalogadas' },
      { value: 0, suffix: 'segredos', label: 'guardados uma da outra (impossível)' },
    ],
    letter: 'Carol, dizem que amizade de escola não sobrevive à vida adulta. A gente sobreviveu a provas, boys errados, mudanças de cidade e àquele seu corte de cabelo de 2014 (que eu apoiei porque amiga apoia até o erro). Você é a irmã que eu escolhi numa cadeira vazia. Obrigada por 15 anos de sorvete de madrugada e verdade na cara. Que a gente vire duas velhinhas fofocando no mesmo grupo. — Bia',
    closing: '◄◄ amizade boa a gente rebobina e assiste de novo',
  },
  {
    slug: 'amizade-republica', persona: 'amigos', occasion: 'amizade',
    name: 'A república que virou família', sortOrder: 37,
    title: 'A república que virou família', recipient: 'os 5 da Casa 42', sender: 'um de nós (vocês sabem qual)',
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 3 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '2016', title: 'Cinco estranhos, uma casa', description: 'Caindo aos pedaços e um sofá achado na rua (nosso patrimônio).' },
      { date: '2017', title: 'Matemática de amizade', description: 'O miojo coletivo de fim de mês: 4 pacotes, 5 pessoas.' },
      { date: '2018', title: 'A TCC WAR', description: 'Revezamos o notebook bom e ninguém dormiu por uma semana. Todos passaram.' },
      { date: '2020', title: 'República virtual', description: 'A pandemia nos separou de casa. Chamada de 4 horas num domingo qualquer.' },
      { date: '2026', title: 'Cláusula pétrea', description: 'Cada um numa cidade. Encontro anual da Casa 42: décima edição confirmada.' },
    ],
    stats: [
      { value: 10, suffix: 'anos', label: 'de Casa 42' },
      { value: 1, suffix: 'sofá', label: 'lendário (in memoriam)' },
      { value: 5, suffix: 'pessoas', label: '1 endereço emocional' },
    ],
    letter: 'Gente, a Casa 42 tinha infiltração, um sofá suspeito e a melhor população por metro quadrado do Brasil. A gente dividiu miojo, boleto, surto de TCC e crise existencial — e multiplicou tudo que importa. Dez anos depois, em cinco cidades diferentes, eu ainda chamo vocês de casa. Que nunca falte pauta no grupo e cadeira no encontro anual. Amo vocês, seus lixos. — Um de nós (vocês sabem qual)',
  },
  {
    slug: 'amizade-um-oceano', persona: 'amigas', occasion: 'amizade',
    name: 'Amizade além-mar', sortOrder: 38,
    title: 'Um oceano e nenhuma distância', recipient: 'Lu', sender: 'sua dinda de longe favorita',
    counter: { targetDate: '2017-03-10', label: 'dias sendo melhores amigas em fuso diferente' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 3 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '2008', title: 'A blusa feia', description: 'A gente se conheceu brigando pela mesma blusa na liquidação. A blusa era feia. A amizade, linda.' },
      { date: '2015', title: 'O chá de despedida', description: 'Eu fiz um discurso, chorei mais que você e roubei sua blusa (a feia). Justiça.' },
      { date: '2017', title: 'A ligação das 4h', description: 'Fuso, né. O pedido de casamento. Eu gritei. O prédio ouviu. Valeu.' },
      { date: '2021', title: 'Dinda de longe', description: 'Sua filha nasceu e eu ganhei o cargo. Exerço com envio mensal de mimo.' },
      { date: '2026', title: 'O oceano perdeu', description: '18 anos de amizade, 9 deles com um oceano no meio.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias vencendo o fuso' },
      { value: 7700, suffix: 'km', label: 'que não valem nada' },
      { value: 1, suffix: '"tô indo aí"', label: 'por ano que sustenta tudo' },
    ],
    letter: 'Lu, a gente mede distância errado. Não são 7.700 km — são 2 horas de fuso, 1 áudio por dia e 1 "tô indo aí" por ano que sustenta tudo. Você do outro lado do mapa continua sendo a primeira pessoa pra quem eu conto qualquer coisa. Amizade de verdade não pede endereço, pede presença — e você nunca faltou. A blusa feia continua comigo. A vaga de melhor amiga também. Pra sempre. — Sua dinda de longe favorita',
    closing: '◄◄ dá play que a saudade rebobina',
  },
  {
    slug: 'amizade-irmaos-da-vida', persona: 'amigos', occasion: 'amizade',
    name: 'Irmãos que a vida escolheu', sortOrder: 39,
    title: 'Irmãos que a vida escolheu', recipient: 'Léo', sender: 'Serginho, 30 anos de rua sem saída',
    counter: { targetDate: '1996-01-15', label: 'dias desde o gol de placa na rua sem saída' },
    photos: [{ n: 1, tl: 1 }, { n: 2, tl: 2 }, { n: 3, tl: 4 }, { n: 4, tl: 5 }],
    timeline: [
      { date: '1996', title: 'A janela quebrada', description: 'Você mudou pra rua e quebrou minha janela com uma bicicleta de bola no primeiro dia. Amizade selada.' },
      { date: '2002', title: 'Diplomacia avançada', description: 'O verão inteiro no videogame emprestado: 1 controle, revezamento por morte.' },
      { date: '2010', title: 'Ficar do lado', description: 'Seu pai faleceu. Eu não sabia o que dizer. Fiquei. Você depois disse que era isso.' },
      { date: '2019/2023', title: 'Família no cartório', description: 'Padrinho do meu casamento; eu, padrinho do seu filho.' },
      { date: '2026', title: '30 anos', description: 'Menos cabelo, mesma resenha, e o combinado do dominó aos 80 tá de pé.' },
    ],
    stats: [
      { auto: 'days_since_counter', label: 'dias de irmandade' },
      { value: 1, suffix: 'janela', label: 'quebrada (dívida perdoada)' },
      { value: 2, suffix: 'famílias', label: 'que viraram 1' },
    ],
    letter: 'Léo, homem não fala dessas coisas, então vou escrever de uma vez e a gente nunca mais toca no assunto: você é o irmão que a vida me deu por acidente (literalmente, minha janela que o diga). 30 anos de zoeira, silêncio nas horas difíceis e presença em todas. Meu filho te chama de tio e não sabe o quanto isso é verdade. Obrigado por tudo, seu ruim de bola. Dominó aos 80 tá mantido. — Serginho',
  },
];
