-- Seed idempotente do exemplo "A mulher do 'já comeu?'" (Dia das Mães, F2-5).
-- Filha adulta homenageando a mãe. Upsert por seoSlug: re-aplicar atualiza o
-- conteúdo sem duplicar. payload no schema de Gift.payload, sem contador, com
-- 4 fotos no R2 (assets) associadas aos momentos via photoAssetId.
INSERT INTO "Example" ("id", "persona", "name", "occasion", "payload", "seoSlug", "sortOrder", "active", "createdAt") VALUES
  ('ex_maes_ja_comeu', 'mãe', 'A mulher do ''já comeu?''', 'pais',
   '{"title":"A mulher do ''já comeu?''","recipientName":"Dona Regina, minha primeira casa","senderName":"sua filha","assets":[{"id":"ph_phone","type":"image","r2Key":"gifts/5501dfdff75c2b9b0f697b61ee618bec.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/5501dfdff75c2b9b0f697b61ee618bec.webp","order":0},{"id":"ph_bus","type":"image","r2Key":"gifts/cc00c0dc7cb881c9ffaf2a87c7205873.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/cc00c0dc7cb881c9ffaf2a87c7205873.webp","order":1},{"id":"ph_maquina","type":"image","r2Key":"gifts/06a5eea45c5ff35e12d8f7f8e3173b6d.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/06a5eea45c5ff35e12d8f7f8e3173b6d.webp","order":2},{"id":"ph_cozinha","type":"image","r2Key":"gifts/0d821762784952d23bd8f6210be678c9.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/0d821762784952d23bd8f6210be678c9.webp","order":3}],"timeline":[{"date":"Desde sempre","title":"O telefone das 12h30","description":"''Filha, já comeu?'' Todo dia em ponto. O relógio da minha vida é você.","photoAssetId":"ph_phone"},{"date":"2002","title":"A febre de madrugada","description":"Você atravessou a cidade de ônibus com sopa num pote de sorvete.","photoAssetId":"ph_bus"},{"date":"2010","title":"A máquina de costura","description":"Você vendeu a sua pra pagar meu cursinho. Descobri anos depois. Nunca esqueci.","photoAssetId":"ph_maquina"},{"date":"2017","title":"Minha mudança","description":"Pra outra cidade. Você chorou depois que o carro virou a esquina (o vizinho contou)."},{"date":"2026","title":"Hoje","description":"Sou eu que ligo 12h30 em ponto. ''Mãe, já comeu?''","photoAssetId":"ph_cozinha"}],"stats":[{"value":8700,"suffix":"ligações de ''já comeu''","label":"e nenhuma perdida"},{"value":1,"suffix":"máquina de costura","label":"que virou diploma"},{"suffix":"∞","label":"potes de sorvete com sopa"}],"letter":"Mãe, demorei a vida inteira pra entender que ''já comeu?'' significa ''eu te amo mais do que sei dizer''. Que sopa em pote de sorvete é declaração. Que máquina de costura vendida em silêncio é o maior discurso que já ouvi. Você me ensinou amor do jeito mais difícil de retribuir: sem cobrar nada. Hoje sou eu que ligo. Já comeu, mãe? Porque o meu coração, você alimentou pra sempre. — Sua filha","closingMessage":"◄◄ toda história começa com ela","spotifyTrackUrl":"https://open.spotify.com/track/2ZC8sdv4Kvuql7Q9T8Agzv","theme":"vhs"}'::jsonb,
   'maes-ja-comeu', 0, true, CURRENT_TIMESTAMP)
ON CONFLICT ("seoSlug") DO UPDATE SET
  "persona" = EXCLUDED."persona",
  "name" = EXCLUDED."name",
  "occasion" = EXCLUDED."occasion",
  "payload" = EXCLUDED."payload",
  "sortOrder" = EXCLUDED."sortOrder",
  "active" = EXCLUDED."active";
