-- Seed idempotente do exemplo "Nossos 1.095 dias de nós" (F2-5).
-- Namoro à distância, 3 anos / 1.095 dias. Upsert por seoSlug: re-aplicar
-- atualiza o conteúdo sem duplicar. payload usa o schema de Gift.payload,
-- com 4 fotos no R2 (assets) associadas aos momentos via photoAssetId.
INSERT INTO "Example" ("id", "persona", "name", "occasion", "payload", "seoSlug", "sortOrder", "active", "createdAt") VALUES
  ('ex_namoro_1095', 'namorada', 'Namoro à distância', 'namorados',
   '{"title":"Nossos 1.095 dias de nós","recipientName":"Bruno","senderName":"Lia","counter":{"targetDate":"2023-07-14","label":"dias sendo nós dois"},"assets":[{"id":"ph_rodoviaria","type":"image","r2Key":"gifts/d8c6a6dafa6042e2b36c6c3ca898604f.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/d8c6a6dafa6042e2b36c6c3ca898604f.webp","order":0},{"id":"ph_mudanca","type":"image","r2Key":"gifts/aa88a3afdbd512a45e491c9dea7566e3.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/aa88a3afdbd512a45e491c9dea7566e3.webp","order":1},{"id":"ph_cozinha","type":"image","r2Key":"gifts/b20e3067ed343dd7010defdfa4cb758f.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/b20e3067ed343dd7010defdfa4cb758f.webp","order":2},{"id":"ph_hoje","type":"image","r2Key":"gifts/11d3edcbc1cbc1ef9203a41b8447f864.webp","url":"https://pub-8f28e4405c4f45469ff2b69fce520c5c.r2.dev/gifts/11d3edcbc1cbc1ef9203a41b8447f864.webp","order":3}],"timeline":[{"date":"14/07/2023","title":"O primeiro oi","description":"No aniversário da Carol. Você riu da minha piada ruim. Eu soube ali."},{"date":"09/2023","title":"412 km de distância","description":"A gente dormia em chamada de vídeo e acordava com o celular quente."},{"date":"12/2023","title":"A surpresa na rodoviária","description":"Você apareceu com um cartaz escrito \"vim buscar meu wi-fi de abraço\".","photoAssetId":"ph_rodoviaria"},{"date":"06/2024","title":"A mudança","description":"Duas malas, uma caixa de livros e zero arrependimento.","photoAssetId":"ph_mudanca"},{"date":"03/2025","title":"Nossa primeira cozinha","description":"Você errou o ponto do brigadeiro e a gente comeu de colher mesmo.","photoAssetId":"ph_cozinha"},{"date":"07/2026","title":"Hoje","description":"Mesmo sofá, mesma piada ruim, mesmo eu sabendo.","photoAssetId":"ph_hoje"}],"stats":[{"value":1095,"suffix":"dias","label":"sendo nós dois"},{"value":14600,"suffix":"minutos","label":"de chamada de vídeo"},{"value":8,"suffix":"rodoviárias","label":"de \"cheguei\""}],"letter":"Bruno, a gente começou contando quilômetros e hoje conta só os dias — e olha que número bonito deu. Obrigada por cada ônibus lotado, por cada ''chegando'' que demorava três horas, por ter feito da distância uma fase e não uma desculpa. Você é minha pessoa favorita de acordar do lado, mesmo quando rouba o edredom inteiro. Que venham os próximos mil dias, de preferência todos com brigadeiro no ponto errado. Te amo. — Lia","spotifyTrackUrl":"https://open.spotify.com/track/18zXw7VA97aovBwbxSpPqH","closingMessage":"◄◄ rebobina que eu quero viver de novo","theme":"vhs"}'::jsonb,
   'namoro-1095-dias', 0, true, CURRENT_TIMESTAMP)
ON CONFLICT ("seoSlug") DO UPDATE SET
  "persona" = EXCLUDED."persona",
  "name" = EXCLUDED."name",
  "occasion" = EXCLUDED."occasion",
  "payload" = EXCLUDED."payload",
  "sortOrder" = EXCLUDED."sortOrder",
  "active" = EXCLUDED."active";
